name: Build & Publish to (Test)PyPI

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install build
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Test package installation
        run: |
          pip install -e .
          system-metrics-easy --help
          system-metrics-easy --status

      - name: Build sdist & wheel
        run: python -m build

      - name: Publish to TestPyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
